baseURL = "https://arminlausterer.github.io"
languageCode = "de-de"
theme = "lausterer"
title = "Armin Lausterer"
[[menu.footer]]
name = "Live Call"
url = "https://us02web.zoom.us/j/2876795051"
weight = 4
[[menu.main]]
name = "Live Call"
url = "https://us02web.zoom.us/j/2876795051"
weight = 8
